all files

diff --git a/cloud deployments/apacheds/Dockerfile b/cloud deployments/apacheds/Dockerfile
--- a/cloud deployments/apacheds/Dockerfile
+++ b/cloud deployments/apacheds/Dockerfile
@@ -1,12 +1,39 @@
 # cloud deployments/apacheds/Dockerfile
 FROM apachedirectory/apacheds:2.0.0.AM26
 
-# custom wrapper.conf with JAVA_HOME=/usr/lib/jvm/jdk1.7.0_80
-COPY config/wrapper.conf /opt/apacheds/conf/wrapper.conf
+USER root
 
-# import Fortress schema
+# 1) Install OS packages & clean up in one layer
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    ca-certificates \
+    bzip2 \
+    unzip \
+    xz-utils; \
+    rm -rf /var/lib/apt/lists/*
+
+# 2) Force UTF-8 locale
+ENV LANG=C.UTF-8 \
+    LANGUAGE=C.UTF-8 \
+    LC_ALL=C.UTF-8
+
+# 3) Copy configs and schema
+COPY config/wrapper.conf \
+    /opt/apacheds/conf/wrapper.conf
+
 COPY ../fortress-core-2.0.0-RC1/ldap/schema/apacheds-fortress.ldif \
     /opt/apacheds/schema/apacheds-fortress.ldif
 
+# 4) Copy and enable our entrypoint script
+COPY apacheds.sh \
+    /opt/apacheds/bin/apacheds.sh
+
+RUN chmod +x /opt/apacheds/bin/apacheds.sh
+
+# 5) Drop privileges
+USER apacheds
+
+# 6) Expose LDAP port & launch via our script
 EXPOSE 389
-# (Entrypoint already starts ApacheDS)
+ENTRYPOINT ["/opt/apacheds/bin/apacheds.sh", "start", "--root"]
diff --git a/cloud deployments/fortress/Dockerfile b/cloud deployments/fortress/Dockerfile
--- a/cloud deployments/fortress/Dockerfile
+++ b/cloud deployments/fortress/Dockerfile
@@ -1,37 +1,45 @@
 # cloud deployments/fortress/Dockerfile
+FROM tomcat:8.5.20-jre8
 
-# 1) Builder stage
-FROM maven:3.6-jdk-7 AS builder
-WORKDIR /build
+USER root
 
-COPY fortress-core-2.0.0-RC1 /build/fortress-core
-RUN cd fortress-core \
-    && cp build.properties.example build.properties \
-    && mvn clean install -Dload.file=./ldap/setup/refreshLDAPData.xml
+# 1) Install only needed OS packages & clean up
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+    ca-certificates \
+    curl \
+    bzip2 \
+    unzip \
+    xz-utils; \
+    rm -rf /var/lib/apt/lists/*
 
-COPY fortress-rest-2.0.0-RC1 /build/fortress-rest
-RUN cd fortress-rest && mvn clean package
+# 2) Ensure UTF-8 locale
+ENV LANG=C.UTF-8 \
+    LANGUAGE=C.UTF-8 \
+    LC_ALL=C.UTF-8
 
-COPY fortress-web-2.0.0-RC1 /build/fortress-web
-RUN cd fortress-web \
-    && cp ../fortress-core/config/fortress.properties src/main/resources/ \
-    && mvn clean package
+# 3) Overlay your custom catalina script
+COPY catalina /usr/local/tomcat/bin/catalina.sh
+RUN chmod +x /usr/local/tomcat/bin/catalina.sh
 
-# 2) Runtime stage
-FROM tomcat:8.5.11-jre7
-LABEL app=fortress
+# 4) Add the Fortress realm-proxy JAR into Tomcat’s lib
+COPY fortress-realm-proxy-2.0.0-RC1.jar \
+    /usr/local/tomcat/lib/fortress-realm-proxy.jar
 
-# overlay manager users
-COPY config/tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
-
-# realm proxy
-COPY --from=builder /build/fortress-core/fortress-realm-proxy/target/fortress-realm-proxy-2.0.0-RC1.jar \
-    /usr/local/tomcat/lib/
-
-# deploy WARs
-COPY --from=builder /build/fortress-rest/target/fortress-rest.war \
+# 5) Deploy the two web apps
+COPY fortress-rest.war \
     /usr/local/tomcat/webapps/fortress-rest.war
-COPY --from=builder /build/fortress-web/target/fortress-web.war \
+COPY fortress-web.war \
     /usr/local/tomcat/webapps/fortress-web.war
 
+# 6) Use your tomcat-users.xml for manager GUI / realm config
+COPY tomcat-users.xml \
+    /usr/local/tomcat/conf/tomcat-users.xml
+
+# 7) Drop back to Tomcat’s unprivileged user
+USER tomcat
+
+# 8) Expose HTTP and launch Tomcat
 EXPOSE 8080
+ENTRYPOINT ["catalina.sh", "run"]
